/* Ideas from the former Crucible sub-site, merged into Toolshed.
 * These are tools/capabilities that need building, not existing software.
 * Appended to window.SOFTWARE so they appear alongside regular entries. */
(window.SOFTWARE = window.SOFTWARE || []).push(
  {
    "id": "lease-clause-comparator",
    "name": "Lease Clause Comparator",
    "description": "Compare two lease agreements by extracting clauses, normalizing them into a taxonomy, and producing a side-by-side diff with severity flags. Tenants and small landlords miss critical differences buried in 30+ pages of legalese.",
    "url": "",
    "category": "Accounting & Finance",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "legal", "documents", "comparison", "pdf"],
    "status": "idea",
    "complexity": "week",
    "capability": "Semantic document comparison with structured clause extraction",
    "approach": "Static site with client-side PDF parsing and API calls to Claude. Upload two PDFs, AI extracts and normalizes clauses, then diffs them.",
    "agentArchitecture": { "model": "steward", "roles": ["steward"] }
  },
  {
    "id": "dependency-health-scorer",
    "name": "Open Source Dependency Health Scorer",
    "description": "Score every dependency in a project on maintainer health, security posture, and community activity. Takes a package manifest, resolves the full tree, pulls data from GitHub, registries, and CVE databases.",
    "url": "",
    "category": "Code Coverage & Quality",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "security", "dependencies", "open-source", "risk", "cli"],
    "status": "idea",
    "complexity": "month",
    "capability": "Multi-signal risk synthesis from heterogeneous data sources",
    "approach": "CLI or web UI. Resolves dependency tree from package.json/requirements.txt/Cargo.toml, scores each dep, produces a risk-ranked dashboard.",
    "agentArchitecture": { "model": "checkpoint", "roles": ["orchestrator", "builder", "analyst", "skeptic"] }
  },
  {
    "id": "meeting-to-actions",
    "name": "Meeting Transcript to Action Items Pipeline",
    "description": "Go from meeting audio to structured action items with owners, deadlines, and confidence scores, pushed directly to your task tracker. No more hand-written summaries that miss things.",
    "url": "",
    "category": "Calendar & Scheduling",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "meetings", "transcription", "automation", "task-management"],
    "status": "idea",
    "complexity": "week",
    "capability": "Structured information extraction from unstructured conversation",
    "approach": "Audio or live mic to Whisper transcription, Claude extracts action items, pushes to Linear/GitHub Issues/Todoist.",
    "agentArchitecture": { "model": "steward", "roles": ["steward"] }
  },
  {
    "id": "codebase-migration-planner",
    "name": "Codebase Migration Planner",
    "description": "Point it at a repo and a migration target (e.g. class components to hooks). AI scans all files, catalogs pattern instances, maps dependencies, and produces a sequenced migration plan with effort estimates per batch.",
    "url": "",
    "category": "Build Tools",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "migration", "refactoring", "codebase", "planning", "automation"],
    "status": "idea",
    "complexity": "month",
    "capability": "Large-scale pattern recognition and dependency-aware transformation planning",
    "approach": "Scan repo, catalog old-pattern instances, map dependencies, sequence changes so nothing breaks mid-migration. Optional: generate the actual PRs.",
    "agentArchitecture": { "model": "protocol-forum", "roles": ["orchestrator", "builder", "strategist", "skeptic", "librarian"] }
  },
  {
    "id": "personal-knowledge-graph",
    "name": "Local-First Personal Knowledge Graph",
    "description": "Import bookmarks, Kindle highlights, markdown notes, and PDF annotations. AI builds a concept graph with semantic relationships — not just keyword matches. Query in natural language. All data stays local.",
    "url": "",
    "category": "Note-Taking & Knowledge",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "knowledge-management", "local-first", "graph", "search", "notes"],
    "status": "idea",
    "complexity": "multi-month",
    "capability": "Semantic relationship discovery across heterogeneous text sources",
    "approach": "Electron or Tauri app. Import from multiple sources, AI builds a graph of concepts and relationships, browse visually or query naturally.",
    "agentArchitecture": { "model": "protocol-forum", "roles": ["orchestrator", "builder", "designer", "strategist", "skeptic"] }
  },
  {
    "id": "git-commit-archaeology",
    "name": "Git Commit Archaeology Tool",
    "description": "Select a code region, and AI traces its full history through commits, PRs, issues, and review comments to produce a narrative of why the code is the way it is. Turns hours of manual excavation into a 30-second query.",
    "url": "",
    "category": "Version Control",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "git", "history", "code-understanding", "cli", "editor-extension"],
    "status": "idea",
    "complexity": "week",
    "capability": "Historical narrative synthesis from fragmented version control data",
    "approach": "CLI or editor extension. Reads git log, finds associated PRs/issues via GitHub API, synthesizes a narrative.",
    "agentArchitecture": { "model": "steward", "roles": ["steward"] }
  },
  {
    "id": "recipe-scaler-substituter",
    "name": "Recipe Scaler & Ingredient Substituter",
    "description": "Paste or photograph a recipe. AI parses it, offers intelligent scaling (with baking ratio adjustments) and context-aware substitutions that account for the specific dish, not just generic swap tables.",
    "url": "",
    "category": "APIs & Services",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "cooking", "recipes", "substitution", "scaling"],
    "status": "in-progress",
    "complexity": "weekend",
    "capability": "Domain-aware numerical reasoning with contextual substitution logic",
    "approach": "Web app. Parse recipe, scale with ratio adjustments, generate context-aware substitutions. Optional dietary restriction mode.",
    "agentArchitecture": { "model": "steward", "roles": ["steward"] }
  },
  {
    "id": "research-paper-debate",
    "name": "Research Paper Debate Simulator",
    "description": "Upload a paper. AI spawns 3-5 agents with different expert perspectives who debate the claims, methodology, and conclusions. Watch the debate, ask follow-ups, get a structured critique with confidence levels.",
    "url": "",
    "category": "AI Assistants",
    "os": [],
    "pricing": "free",
    "tags": ["idea", "papers", "peer-review", "debate", "multi-agent", "education"],
    "status": "idea",
    "complexity": "week",
    "capability": "Multi-perspective critical analysis with adversarial reasoning",
    "approach": "PDF upload, spawn expert agents, run moderated debate, compile structured critique.",
    "agentArchitecture": { "model": "checkpoint", "roles": ["orchestrator", "builder", "analyst", "skeptic"] }
  }
);
